import React, { useState } from 'react';
import { createBooking } from '../../services/booking.service';

const gold = 'var(--accent)';
const goldLight = '#f5d270';

const Icons = {
  Ticket: () => <svg width="18" height="18" viewBox="0 0 24 24" fill="currentColor"><path d="M2 9a3 3 0 0 1 0 6v2a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2v-2a3 3 0 0 1 0-6V7a2 2 0 0 0-2-2H4a2 2 0 0 0-2 2z"/></svg>,
  Check: () => <svg width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="#2ecc71" strokeWidth="2.5"><polyline points="20 6 9 17 4 12"/></svg>,
  Download: () => <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="7 10 12 15 17 10"/><line x1="12" y1="15" x2="12" y2="3"/></svg>,
  Calendar: () => <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><rect x="3" y="4" width="18" height="18" rx="2" ry="2"/><line x1="16" y1="2" x2="16" y2="6"/><line x1="8" y1="2" x2="8" y2="6"/><line x1="3" y1="10" x2="21" y2="10"/></svg>,
  MapPin: () => <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M21 10c0 7-9 13-9 13s-9-6-9-13a9 9 0 0 1 18 0z"/><circle cx="12" cy="10" r="3"/></svg>,
  Tag: () => <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><line x1="12" y1="1" x2="12" y2="23"/><path d="M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6"/></svg>,
  Spin: () => <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" style={{ animation: 'spin 0.8s linear infinite' }}><path d="M21 12a9 9 0 1 1-6.219-8.56"/></svg>,
  CheckSmall: () => <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5"><polyline points="20 6 9 17 4 12"/></svg>,
};

/* ── Invoice generator using jsPDF from CDN window.jspdf ─────────────────── */
const downloadInvoice = (booking, event) => {
  const { jsPDF } = window.jspdf || {};
  if (!jsPDF) {
    const w = window.open('', '_blank');
    w.document.write(`
      <html><head><title>Invoice</title>
      <style>
        body { font-family: Arial,sans-serif; padding: 40px; color: #111; }
        h1 { color: #D4AF37; } hr { border-color: #D4AF3733; }
        .row { display: flex; justify-content: space-between; margin: 8px 0; }
        .label { color: #666; } .val { font-weight: 600; }
        .total { background: #fff8e1; border: 1px solid #D4AF37; padding: 12px 16px; border-radius: 8px; }
      </style></head><body>
      <h1>EventPro — Booking Invoice</h1>
      <hr/>
      <p><strong>Booking ID:</strong> ${booking.id}</p>
      <p><strong>Event:</strong> ${event.title}</p>
      <p><strong>Date:</strong> ${event.date} at ${event.startTime}</p>
      <p><strong>Location:</strong> ${event.location}</p>
      <hr/>
      <p><strong>Customer:</strong> ${booking.customerName || ''}</p>
      <p><strong>Email:</strong> ${booking.customerEmail || ''}</p>
      <p><strong>Phone:</strong> ${booking.customerPhone || ''}</p>
      <hr/>
      <p><strong>Tickets:</strong> ${booking.ticketCount}</p>
      <p><strong>Price per Ticket:</strong> ₹${event.price}</p>
      <p><strong>Total Amount:</strong> ₹${booking.totalAmount}</p>
      <p><strong>Payment Status:</strong> ${(booking.paymentStatus || 'confirmed').toUpperCase()}</p>
      <hr/>
      <p style="color:#888;font-size:12px">Generated by EventPro on ${new Date().toLocaleDateString('en-IN')}</p>
      </body></html>
    `);
    w.document.close();
    w.print();
    return;
  }
  // (Full jsPDF logic remains the same)
  const doc = new jsPDF();
  const pageW = doc.internal.pageSize.getWidth();
  doc.setFillColor(15, 15, 26);
  doc.rect(0, 0, pageW, 45, 'F');
  doc.setFillColor(201, 168, 76);
  doc.rect(0, 43, pageW, 2, 'F');
  doc.setTextColor(245, 210, 112);
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.text('EventPro', 15, 20);
  doc.setFontSize(10);
  doc.setTextColor(150, 150, 150);
  doc.setFont('helvetica', 'normal');
  doc.text('BOOKING INVOICE', 15, 30);
  doc.setTextColor(245, 210, 112);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text(`Invoice #${booking.id}`, pageW - 15, 20, { align: 'right' });
  doc.setTextColor(150, 150, 150);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.text(new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' }), pageW - 15, 30, { align: 'right' });
  let y = 58;
  doc.setFillColor(30, 30, 58);
  doc.roundedRect(10, y - 6, pageW - 20, 42, 3, 3, 'F');
  doc.setTextColor(201, 168, 76);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.text('EVENT DETAILS', 16, y + 2);
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(13);
  doc.text(event.title, 16, y + 12);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(170, 170, 170);
  doc.text(`Date: ${event.date}  |  Time: ${event.startTime}  |  Location: ${event.location}`, 16, y + 22);
  y += 54;
  doc.setFillColor(22, 22, 44);
  doc.roundedRect(10, y - 6, pageW - 20, 52, 3, 3, 'F');
  doc.setTextColor(201, 168, 76);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.text('CUSTOMER INFORMATION', 16, y + 2);
  const custRows = [
    ['Name', booking.customerName || '—'],
    ['Email', booking.customerEmail || '—'],
    ['Phone', booking.customerPhone || '—'],
    ['Location', [booking.customerCity, booking.customerState, booking.customerCountry].filter(Boolean).join(', ') || '—'],
  ];
  custRows.forEach(([label, val], idx) => {
    const ry = y + 12 + idx * 9;
    doc.setTextColor(140, 140, 140);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.text(label, 16, ry);
    doc.setTextColor(220, 220, 220);
    doc.text(val, 70, ry);
  });
  y += 64;
  doc.setFillColor(20, 20, 40);
  doc.roundedRect(10, y - 6, pageW - 20, 38, 3, 3, 'F');
  doc.setTextColor(201, 168, 76);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.text('TICKET SUMMARY', 16, y + 2);
  const tickRows = [
    ['Tickets Booked', `${booking.ticketCount}`],
    ['Price per Ticket', `Rs. ${event.price}`],
    ['Payment Status', (booking.paymentStatus || 'Confirmed').toUpperCase()],
  ];
  tickRows.forEach(([label, val], idx) => {
    const ry = y + 12 + idx * 8;
    doc.setTextColor(140, 140, 140);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.text(label, 16, ry);
    doc.setTextColor(220, 220, 220);
    doc.text(val, 120, ry);
  });
  y += 50;
  doc.setFillColor(201, 168, 76);
  doc.roundedRect(10, y, pageW - 20, 22, 4, 4, 'F');
  doc.setTextColor(15, 15, 26);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.text('TOTAL AMOUNT', 16, y + 14);
  doc.setFontSize(14);
  doc.text(`Rs. ${Number(booking.totalAmount).toFixed(2)}`, pageW - 16, y + 14, { align: 'right' });
  y += 34;
  doc.setTextColor(80, 80, 80);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.text('Thank you for booking with EventPro. This is your official booking confirmation.', pageW / 2, y, { align: 'center' });
  doc.text('For support: support@eventpro.com', pageW / 2, y + 6, { align: 'center' });
  doc.save(`EventPro_Invoice_${booking.id}.pdf`);
};

/* ─────────────────────────────────────────────────────────────────────────── */
const BookingFormModal = ({ event, onClose, onSuccess }) => {
  const [form, setForm] = useState({
    customerName: '', customerEmail: '', customerPhone: '',
    customerCity: '', customerState: '', customerCountry: '',
    company: '', specialNotes: '', ticketCount: 1,
  });
  const [errors, setErrors] = useState({});
  const [loading, setLoading] = useState(false);
  const [apiError, setApiError] = useState('');
  const [successBooking, setSuccessBooking] = useState(null);

  const handle = (e) => {
    const { name, value } = e.target;
    setForm(prev => ({ ...prev, [name]: value }));
    setErrors(prev => ({ ...prev, [name]: '' }));
  };

  const validate = () => {
    const errs = {};
    if (!form.customerName.trim()) errs.customerName = 'Full name is required';
    if (!form.customerEmail.trim()) errs.customerEmail = 'Email is required';
    else if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(form.customerEmail)) errs.customerEmail = 'Enter a valid email';
    if (!form.customerPhone.trim()) errs.customerPhone = 'Mobile number is required';
    if (!form.ticketCount || form.ticketCount < 1) errs.ticketCount = 'At least 1 ticket required';
    if (form.ticketCount > event.capacity) errs.ticketCount = `Only ${event.capacity} tickets available`;
    return errs;
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    const errs = validate();
    if (Object.keys(errs).length) return setErrors(errs);
    setLoading(true);
    setApiError('');
    try {
      const result = await createBooking({ ...form, eventId: event.id, ticketCount: Number(form.ticketCount) });
      const booking = result.booking || result;
      // Skip success card, just redirect to payment page via onSuccess
      onSuccess(booking);
    } catch (err) {
      setApiError(err.response?.data?.message || 'Booking failed. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  const totalAmount = (Number(form.ticketCount) || 0) * (event.price || 0);

  return (
    <>
      <div onClick={onClose} style={{ position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.6)', zIndex: 1040, backdropFilter: 'blur(8px)' }} />
      <div style={{ position: 'fixed', inset: 0, display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 1050, padding: '1rem', fontFamily: "'Inter', sans-serif" }}>
        <div className="card-premium fade-in" style={{
          width: '100%', maxWidth: 640,
          maxHeight: '90vh', overflowY: 'auto',
          boxShadow: '0 32px 100px rgba(0,0,0,0.7)',
          padding: 0,
        }}>
          {/* Header */}
          <div style={{
            background: `linear-gradient(90deg, \${gold}, \${goldLight})`,
            padding: '1.25rem 1.5rem',
            display: 'flex', justifyContent: 'space-between', alignItems: 'center',
          }}>
            <div>
              <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 2 }}>
                <Icons.Ticket />
                <h5 style={{ margin: 0, color: '#0f0f0f', fontWeight: 800, fontSize: 16 }}>Book Tickets</h5>
              </div>
              <small style={{ color: '#222', fontWeight: 600 }}>{event.title}</small>
            </div>
            <button onClick={onClose} style={{ background: 'rgba(0,0,0,0.15)', border: 'none', borderRadius: '50%', width: 32, height: 32, color: '#000', cursor: 'pointer', fontSize: 18, display: 'flex', alignItems: 'center', justifyContent: 'center', transition: 'background 0.2s' }}>×</button>
          </div>

          {/* Success state */}
          {successBooking ? (
            <div style={{ padding: '2.5rem 2rem', textAlign: 'center' }}>
              <div style={{ width: 72, height: 72, borderRadius: '50%', background: 'rgba(46,204,113,0.15)', border: '2px solid #2ecc71', display: 'flex', alignItems: 'center', justifyContent: 'center', margin: '0 auto 1.25rem' }}>
                <Icons.Check />
              </div>
              <h4 style={{ color: '#2ecc71', fontWeight: 700, marginBottom: 8, fontSize: 20 }}>Booking Confirmed!</h4>
              <p style={{ color: 'var(--muted)', fontSize: 14, marginBottom: '2rem' }}>Your booking has been confirmed. Download your invoice below.</p>

              <div style={{ background: 'var(--glass)', border: '1px solid var(--border)', borderRadius: 12, padding: '1.25rem', marginBottom: '2rem', textAlign: 'left' }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 8 }}>
                  <span style={{ color: 'var(--muted)', fontSize: 13 }}>Event</span>
                  <span style={{ color: 'var(--text)', fontSize: 13, fontWeight: 600 }}>{event.title}</span>
                </div>
                <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 8 }}>
                  <span style={{ color: 'var(--muted)', fontSize: 13 }}>Tickets</span>
                  <span style={{ color: 'var(--text)', fontSize: 13, fontWeight: 600 }}>{successBooking.ticketCount}</span>
                </div>
                <div style={{ display: 'flex', justifyContent: 'space-between', paddingTop: 8, borderTop: '1px solid var(--border)' }}>
                  <span style={{ color: 'var(--muted)', fontSize: 13 }}>Total Paid</span>
                  <span style={{ color: goldLight, fontSize: 16, fontWeight: 800 }}>₹{Number(successBooking.totalAmount).toFixed(2)}</span>
                </div>
              </div>

              <div style={{ display: 'flex', gap: '1rem' }}>
                <button onClick={() => downloadInvoice(successBooking, event)} className="btn-gold" style={{ flex: 1, display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 8, padding: '0.8rem' }}>
                  <Icons.Download /> Download Invoice
                </button>
                <button onClick={() => onSuccess(successBooking)} className="btn-outline-gold" style={{ flex: 1, padding: '0.8rem' }}>
                  View My Bookings
                </button>
              </div>
            </div>
          ) : (
            <form onSubmit={handleSubmit} style={{ padding: '1.5rem' }}>
              {apiError && (
                <div style={{ background: 'rgba(231,76,60,0.1)', border: '1px solid rgba(231,76,60,0.3)', borderRadius: 10, padding: '0.75rem', marginBottom: '1.25rem', color: '#e74c3c', fontSize: 13 }}>
                  {apiError}
                </div>
              )}

              {/* Event summary */}
              <div style={{ background: 'var(--glass)', border: '1px solid var(--border)', borderRadius: 10, padding: '1rem', marginBottom: '1.5rem', display: 'flex', flexWrap: 'wrap', gap: '1rem' }}>
                {[
                  { icon: <Icons.Calendar />, label: event.date },
                  { icon: <Icons.MapPin />, label: event.location },
                  { icon: <Icons.Tag />, label: `₹\${event.price}/ticket` },
                ].map((item, i) => (
                  <span key={i} style={{ color: gold, fontSize: 12, display: 'flex', alignItems: 'center', gap: 5, fontWeight: 600 }}>
                    {item.icon} {item.label}
                  </span>
                ))}
              </div>

              <SectionLabel>Customer Details</SectionLabel>

              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1rem', marginBottom: '1rem' }}>
                <Field label="Full Name *" error={errors.customerName}>
                  <input className="input-premium" name="customerName" value={form.customerName} onChange={handle} placeholder="" style={inputSt(errors.customerName)} />
                </Field>
                <Field label="Email Address *" error={errors.customerEmail}>
                  <input className="input-premium" name="customerEmail" type="email" value={form.customerEmail} onChange={handle} placeholder="" style={inputSt(errors.customerEmail)} />
                </Field>
                <Field label="Mobile Number *" error={errors.customerPhone}>
                  <input className="input-premium" name="customerPhone" value={form.customerPhone} onChange={handle} placeholder="" style={inputSt(errors.customerPhone)} />
                </Field>
                <Field label="Number of Tickets *" error={errors.ticketCount}>
                  <input className="input-premium" name="ticketCount" type="number" min={1} max={event.capacity} value={form.ticketCount} onChange={handle} style={inputSt(errors.ticketCount)} />
                </Field>
              </div>

              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: '1rem', marginBottom: '1rem' }}>
                <Field label="City"><input className="input-premium" name="customerCity" value={form.customerCity} onChange={handle} placeholder="" style={inputSt()} /></Field>
                <Field label="State"><input className="input-premium" name="customerState" value={form.customerState} onChange={handle} placeholder="" style={inputSt()} /></Field>
                <Field label="Country"><input className="input-premium" name="customerCountry" value={form.customerCountry} onChange={handle} placeholder="" style={inputSt()} /></Field>
              </div>

              <div style={{ marginBottom: '1rem' }}>
                <Field label="Company (optional)"><input className="input-premium" name="company" value={form.company} onChange={handle} placeholder="" style={inputSt()} /></Field>
              </div>
              <div style={{ marginBottom: '1.5rem' }}>
                <Field label="Special Notes (optional)">
                  <textarea className="input-premium" name="specialNotes" value={form.specialNotes} onChange={handle} rows={3} placeholder="Any special requirements..." style={{ ...inputSt(), resize: 'vertical' }} />
                </Field>
              </div>

              {/* Total */}
              <div style={{ background: 'var(--glass)', border: `1px solid \${gold}`, borderRadius: 10, padding: '1rem 1.25rem', marginBottom: '1.5rem', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                <span style={{ color: 'var(--text)', fontSize: 14 }}>{form.ticketCount} ticket{Number(form.ticketCount) > 1 ? 's' : ''} × ₹{event.price}</span>
                <span style={{ color: goldLight, fontWeight: 800, fontSize: 24 }}>₹{totalAmount.toFixed(2)}</span>
              </div>

              <div style={{ display: 'flex', gap: '1rem' }}>
                <button type="button" onClick={onClose} style={{ flex: 1, padding: '0.8rem', borderRadius: 10, border: '1px solid var(--border)', background: 'transparent', color: 'var(--muted)', cursor: 'pointer', fontWeight: 600, transition: 'background 0.2s' }} onMouseOver={e=>e.target.style.background='var(--glass)'} onMouseOut={e=>e.target.style.background='transparent'}>
                  Cancel
                </button>
                <button type="submit" disabled={loading} className="btn-gold" style={{ flex: 2, padding: '0.8rem', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 8, opacity: loading ? 0.7 : 1, cursor: loading ? 'not-allowed' : 'pointer' }}>
                  {loading
                    ? <><Icons.Spin /> Processing…</>
                    : <><Icons.CheckSmall /> Confirm Booking</>
                  }
                </button>
              </div>
            </form>
          )}
        </div>
      </div>
      <style>{`@keyframes spin { to { transform: rotate(360deg); } }`}</style>
    </>
  );
};

const SectionLabel = ({ children }) => (
  <p style={{ color: gold, fontWeight: 700, fontSize: 11, letterSpacing: 1.2, marginBottom: '1rem', textTransform: 'uppercase' }}>{children}</p>
);

const Field = ({ label, error, children }) => (
  <div>
    <label style={{ display: 'block', color: 'var(--muted)', fontSize: 11, marginBottom: 6, fontWeight: 600, letterSpacing: '0.5px' }}>{label}</label>
    {children}
    {error && <div style={{ color: '#e74c3c', fontSize: 10, marginTop: 4 }}>{error}</div>}
  </div>
);

const inputSt = (hasError) => ({
  width: '100%',
  borderColor: hasError ? '#e74c3c' : undefined,
});

export default BookingFormModal;
