import React, { useState, useEffect } from 'react';
import { getMyBookings, cancelBooking } from '../../services/booking.service';
import { Link } from 'react-router-dom';

const gold = 'var(--accent)';

const statusColor = (s) => s === 'confirmed' ? '#2ecc71' : s === 'cancelled' ? '#e74c3c' : '#f39c12';
const paymentColor = (s) => s === 'paid' ? '#2ecc71' : s === 'pending' ? '#f39c12' : '#e74c3c';

const Icons = {
  Bookings: () => <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14 2 14 8 20 8"/><line x1="16" y1="13" x2="8" y2="13"/><line x1="16" y1="17" x2="8" y2="17"/></svg>,
  MapPin: () => <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M21 10c0 7-9 13-9 13s-9-6-9-13a9 9 0 0 1 18 0z"/><circle cx="12" cy="10" r="3"/></svg>,
  Calendar: () => <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect x="3" y="4" width="18" height="18" rx="2" ry="2"/><line x1="16" y1="2" x2="16" y2="6"/><line x1="8" y1="2" x2="8" y2="6"/><line x1="3" y1="10" x2="21" y2="10"/></svg>,
  CheckCircle: () => <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M22 11.08V12a10 10 0 1 1-5.93-9.14"/><polyline points="22 4 12 14.01 9 11.01"/></svg>,
  Circle: () => <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="10"/></svg>,
  Download: () => <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="7 10 12 15 17 10"/><line x1="12" y1="15" x2="12" y2="3"/></svg>,
};

const downloadInvoice = (booking) => {
  const { jsPDF } = window.jspdf || {};
  const event = booking.Event || {};
  if (!jsPDF) {
    const w = window.open('', '_blank');
    w.document.write(`
      <html><head><title>Invoice #${booking.id}</title>
      <style>body{font-family:Arial,sans-serif;padding:40px;color:#111}h1{color:#c9a84c}hr{border-color:#c9a84c33}p{margin:6px 0}</style>
      </head><body>
      <h1>EventPro — Booking Invoice</h1><hr/>
      <p><strong>Booking ID:</strong> ${booking.id}</p>
      <p><strong>Event:</strong> ${event.title || '—'}</p>
      <p><strong>Date:</strong> ${event.date || '—'}</p>
      <p><strong>Location:</strong> ${event.location || '—'}</p>
      <hr/>
      <p><strong>Customer:</strong> ${booking.customerName || '—'}</p>
      <p><strong>Email:</strong> ${booking.customerEmail || '—'}</p>
      <p><strong>Phone:</strong> ${booking.customerPhone || '—'}</p>
      <hr/>
      <p><strong>Tickets:</strong> ${booking.ticketCount}</p>
      <p><strong>Total:</strong> ₹${booking.totalAmount}</p>
      <p><strong>Status:</strong> ${booking.paymentStatus || 'pending'}</p>
      <hr/><p style="color:#888;font-size:12px">Generated by EventPro on ${new Date().toLocaleDateString('en-IN')}</p>
      </body></html>
    `);
    w.document.close(); w.print(); return;
  }
  // Invoice generation logic (unchanged)
  const doc = new jsPDF();
  const pageW = doc.internal.pageSize.getWidth();
  doc.setFillColor(15, 15, 26);
  doc.rect(0, 0, pageW, 45, 'F');
  doc.setFillColor(201, 168, 76);
  doc.rect(0, 43, pageW, 2, 'F');
  doc.setTextColor(245, 210, 112);
  doc.setFontSize(22); doc.setFont('helvetica', 'bold');
  doc.text('EventPro', 15, 20);
  doc.setFontSize(10); doc.setTextColor(150, 150, 150); doc.setFont('helvetica', 'normal');
  doc.text('BOOKING INVOICE', 15, 30);
  doc.setTextColor(245, 210, 112); doc.setFontSize(11); doc.setFont('helvetica', 'bold');
  doc.text(`Invoice #${booking.id}`, pageW - 15, 20, { align: 'right' });
  doc.setTextColor(150, 150, 150); doc.setFont('helvetica', 'normal'); doc.setFontSize(9);
  doc.text(new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' }), pageW - 15, 30, { align: 'right' });

  let y = 58;
  doc.setFillColor(30, 30, 58); doc.roundedRect(10, y - 6, pageW - 20, 38, 3, 3, 'F');
  doc.setTextColor(201, 168, 76); doc.setFontSize(9); doc.setFont('helvetica', 'bold');
  doc.text('EVENT DETAILS', 16, y + 2);
  doc.setTextColor(255, 255, 255); doc.setFontSize(13);
  doc.text(event.title || '—', 16, y + 12);
  doc.setFontSize(9); doc.setFont('helvetica', 'normal'); doc.setTextColor(170, 170, 170);
  doc.text(`Date: ${event.date || '—'}  |  Location: ${event.location || '—'}`, 16, y + 22);

  y += 50;
  doc.setFillColor(22, 22, 44); doc.roundedRect(10, y - 6, pageW - 20, 46, 3, 3, 'F');
  doc.setTextColor(201, 168, 76); doc.setFontSize(9); doc.setFont('helvetica', 'bold');
  doc.text('CUSTOMER INFORMATION', 16, y + 2);
  [['Name', booking.customerName], ['Email', booking.customerEmail], ['Phone', booking.customerPhone], ['Location', [booking.customerCity, booking.customerState, booking.customerCountry].filter(Boolean).join(', ') || '—']].forEach(([l, v], idx) => {
    doc.setTextColor(140, 140, 140); doc.setFont('helvetica', 'normal'); doc.setFontSize(9);
    doc.text(l, 16, y + 12 + idx * 8);
    doc.setTextColor(220, 220, 220); doc.text(v || '—', 70, y + 12 + idx * 8);
  });

  y += 58;
  doc.setFillColor(201, 168, 76); doc.roundedRect(10, y, pageW - 20, 22, 4, 4, 'F');
  doc.setTextColor(15, 15, 26); doc.setFont('helvetica', 'bold'); doc.setFontSize(12);
  doc.text(`Tickets: ${booking.ticketCount}  |  Total: Rs. ${Number(booking.totalAmount).toFixed(2)}`, 16, y + 14);

  y += 34;
  doc.setTextColor(80, 80, 80); doc.setFont('helvetica', 'normal'); doc.setFontSize(8);
  doc.text('Thank you for booking with EventPro.', pageW / 2, y, { align: 'center' });

  doc.save(`EventPro_Invoice_${booking.id}.pdf`);
};

const TimelineItem = ({ label, active, last }) => (
  <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', flex: 1, position: 'relative' }}>
    <div style={{ zIndex: 1, color: active ? '#2ecc71' : 'var(--muted)', background: 'var(--card)' }}>
      {active ? <Icons.CheckCircle /> : <Icons.Circle />}
    </div>
    <div style={{ marginTop: 8, fontSize: 11, color: active ? 'var(--text)' : 'var(--muted)', textAlign: 'center', fontWeight: active ? 600 : 400 }}>
      {label}
    </div>
    {!last && (
      <div style={{ position: 'absolute', top: 7, left: '50%', width: '100%', height: 2, background: active ? '#2ecc71' : 'var(--border)', zIndex: 0 }} />
    )}
  </div>
);

const MyBookings = () => {
  const [bookings, setBookings] = useState([]);
  const [loading, setLoading] = useState(true);
  const [cancelling, setCancelling] = useState(null);

  useEffect(() => { fetchBookings(); }, []);

  const fetchBookings = async () => {
    try {
      const data = await getMyBookings();
      setBookings(data);
    } catch (err) {
      console.error('Failed to fetch bookings', err);
    } finally {
      setLoading(false);
    }
  };

  const handleCancel = async (id) => {
    if (!window.confirm('Cancel this booking?')) return;
    setCancelling(id);
    try {
      await cancelBooking(id);
      setBookings(prev => prev.filter(b => b.id !== id));
    } catch (err) {
      alert(err.response?.data?.message || 'Failed to cancel');
    } finally {
      setCancelling(null);
    }
  };

  if (loading) return (
    <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', minHeight: '50vh', flexDirection: 'column', gap: 16 }}>
      <div className="spinner-border" style={{ color: gold, width: 44, height: 44 }} />
      <p style={{ color: 'var(--muted)' }}>Loading your bookings…</p>
    </div>
  );

  return (
    <div style={{ maxWidth: 1200, margin: '0 auto', padding: '2rem 1.5rem', fontFamily: "'Inter', sans-serif" }}>
      <div style={{ marginBottom: '2rem' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
          <div style={{ color: gold }}>
            <Icons.Bookings />
          </div>
          <div>
            <h1 style={{ color: 'var(--accent)', fontWeight: 800, fontSize: 24, margin: 0 }}>My Bookings</h1>
            <p style={{ color: 'var(--muted)', fontSize: 13, margin: 0 }}>All your event ticket bookings in one place</p>
          </div>
        </div>
      </div>

      {bookings.length === 0 ? (
        <div style={{ textAlign: 'center', marginTop: '3rem', background: 'var(--glass)', border: '1px dashed var(--border)', borderRadius: 18, padding: '4rem 2rem' }}>
          <div style={{ color: gold, marginBottom: 16 }}><Icons.Bookings /></div>
          <h4 style={{ color: gold, marginBottom: 8 }}>No bookings yet</h4>
          <p style={{ color: 'var(--muted)', marginBottom: '1.5rem', fontSize: 14 }}>Discover events and book your first ticket!</p>
          <Link to="/attender/events" className="btn-gold" style={{ textDecoration: 'none', display: 'inline-block' }}>
            Browse Events
          </Link>
        </div>
      ) : (
        <div style={{ display: 'flex', flexDirection: 'column', gap: '1.5rem' }}>
          {bookings.map((booking) => {
            const isPaid = booking.paymentStatus === 'paid';
            const isConfirmed = booking.status === 'confirmed';
            
            return (
              <div key={booking.id} className="card-premium fade-in" style={{ padding: '1.5rem' }}>
                <div style={{ display: 'flex', flexWrap: 'wrap', gap: '2rem', alignItems: 'flex-start' }}>
                  
                  {/* Image & Basic Details */}
                  <div style={{ flex: '1 1 300px', display: 'flex', gap: '1rem' }}>
                    <div style={{ width: 100, height: 100, borderRadius: 12, background: 'var(--border)', flexShrink: 0, backgroundImage: `url(\${booking.Event?.imageUrl || 'https://via.placeholder.com/150/1a1a1a/D4AF37?text=Event'})`, backgroundSize: 'cover', backgroundPosition: 'center' }} />
                    <div>
                      <span style={{ fontSize: 10, color: 'var(--muted)' }}>Booking <span style={{ color: gold, fontWeight: 700 }}>#{booking.id}</span></span>
                      <h4 style={{ color: 'var(--text)', fontWeight: 800, fontSize: 18, margin: '4px 0 8px' }}>{booking.Event?.title || 'Event'}</h4>
                      
                      <div style={{ display: 'flex', alignItems: 'center', gap: 6, color: 'var(--muted)', fontSize: 12, marginBottom: 6 }}>
                        <Icons.Calendar /> {booking.Event?.date || '—'}
                      </div>
                      <div style={{ display: 'flex', alignItems: 'center', gap: 6, color: 'var(--muted)', fontSize: 12 }}>
                        <Icons.MapPin /> {booking.Event?.location || '—'}
                      </div>
                    </div>
                  </div>

                  {/* Timeline */}
                  <div style={{ flex: '2 1 400px', alignSelf: 'center' }}>
                    <div style={{ display: 'flex', justifyContent: 'space-between', padding: '1rem 0' }}>
                      <TimelineItem label="Request Sent" active={true} />
                      <TimelineItem label="Payment Completed" active={isPaid} />
                      <TimelineItem label="Organizer Accepted" active={isConfirmed} />
                      <TimelineItem label="Event Scheduled" active={isConfirmed} last={true} />
                    </div>
                  </div>

                  {/* Actions & Price */}
                  <div style={{ flex: '1 1 200px', display: 'flex', flexDirection: 'column', gap: 12, borderLeft: '1px solid var(--border)', paddingLeft: '1.5rem' }}>
                    <div>
                      <div style={{ color: 'var(--muted)', fontSize: 12 }}>Total Amount</div>
                      <div style={{ color: gold, fontWeight: 800, fontSize: 24 }}>₹{booking.totalAmount?.toFixed(2)}</div>
                    </div>
                    <div>
                      <div style={{ color: 'var(--muted)', fontSize: 12 }}>Tickets: <strong style={{ color: 'var(--text)' }}>{booking.ticketCount}</strong></div>
                    </div>
                    <div style={{ display: 'flex', gap: 8, marginTop: 'auto' }}>
                       <button
                        onClick={() => downloadInvoice(booking)}
                        className="btn-outline-gold"
                        style={{ display: 'flex', alignItems: 'center', gap: 6, flex: 1, justifyContent: 'center' }}
                      >
                        <Icons.Download /> Invoice
                      </button>
                      {booking.status !== 'cancelled' && (
                        <button
                          onClick={() => handleCancel(booking.id)}
                          disabled={cancelling === booking.id}
                          style={{ padding: '6px 12px', fontSize: 12, borderRadius: 12, border: '1px solid #e74c3c', background: 'transparent', color: '#e74c3c', cursor: 'pointer', flex: 1 }}
                        >
                          {cancelling === booking.id ? '...' : 'Cancel'}
                        </button>
                      )}
                    </div>
                  </div>

                </div>
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
};

export default MyBookings;
